# ============================================================
#  Configuration Mosquitto - Smart Parking
#  Fichier : mosquitto/config/mosquitto.conf
# ============================================================

# Port d'écoute MQTT standard
listener 1883

# Port WebSocket (optionnel, pour tests depuis navigateur)
listener 9001
protocol websockets

# Autoriser les connexions sans authentification
# (à sécuriser en production avec un fichier password)
allow_anonymous true

# Persistance des messages
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all